### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by WarlockAUS** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#20]
trying to run the code and i get connection refused from both a windows and linux machine.

Logging in...
Logged in.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

**Comment by PiotrMachowski** [comment]
Do you use a firewall/advised/pihole?

**Comment by WarlockAUS** [comment]
I have a pi-hole yes, but i can't see the traffic being blocked.  i will bypass and try again.

**Comment by WarlockAUS** [comment]
Bam! ... thank you Sir  :)

**Comment by PiotrMachowski** [comment]
👍
