### ISSUE TITLE
Logged in, but error afterward

### ISSUE THREAD

**Issue by hudarsono** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#34]
Here is the log : 
```
Logging in...
Logged in.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1639, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')
```

Any idea?

**Comment by PiotrMachowski** [comment]
It can be because of traffic being blocked by: DNS (Cloudflare), PiHole/AdGuard, firewall, etc. Can you check if it applies to your case?

**Comment by igenkin** [comment]
I had the same when I tried to use all servers ('blank' for the server). Try to use only one server at a time. It worked for me.

**Comment by hudarsono** [comment]
It worked when I use the docker version.
