### ISSUE TITLE
error on token_extractor.exe

### ISSUE THREAD

**Issue by Yarden92** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#39]
After I enter my mail, password and contry (correctly, verified on app), I get the following traceback error:

```Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 677, in urlopen
  File "urllib3\connectionpool.py", line 381, in _make_request
  File "urllib3\connectionpool.py", line 978, in _validate_conn
  File "urllib3\connection.py", line 371, in connect
  File "urllib3\util\ssl_.py", line 384, in ssl_wrap_socket
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 449, in send
  File "urllib3\connectionpool.py", line 727, in urlopen
  File "urllib3\util\retry.py", line 439, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='account.xiaomi.com', port=443): Max retries exceeded with url: /pass/serviceLogin?sid=xiaomiio&_json=true (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "token_extractor.py", line 217, in <module>
  File "token_extractor.py", line 97, in login
  File "token_extractor.py", line 42, in login_step_1
  File "requests\sessions.py", line 543, in get
  File "requests\sessions.py", line 530, in request
  File "requests\sessions.py", line 643, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='account.xiaomi.com', port=443): Max retries exceeded with url: /pass/serviceLogin?sid=xiaomiio&_json=true (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)')))
[18268] Failed to execute script token_extractor```

**Comment by PiotrMachowski** [comment]
Please check out issue #18

**Comment by Yarden92** [comment]
Right right! the work PC was blocking my network, probably firewalls and stuffs.. works fine on my personal macbook, thanks!
