### ISSUE TITLE
Token extractor generates list of error

### ISSUE THREAD

**Issue by drorya1** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#60]
While my "Xiaomi Robot " did not show anymore in HA I assumed it related to lost token .
When trying to run to token extractor I get the following errors 

Username (email or user ID):
dxxxxx@gmail.com
Password:
xxxxxxx
Server (one of: cn, de, us, ru, tw, sg, in, i2) Leave empty to check all available:

Logging in...
Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 706, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 382, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
  File "site-packages\urllib3\connection.py", line 426, in connect
  File "site-packages\urllib3\util\ssl_.py", line 450, in ssl_wrap_socket
  File "site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 756, in urlopen
  File "site-packages\urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='account.xiaomi.com', port=443): Max retries exceeded with url: /pass/serviceLogin?sid=xiaomiio&_json=true (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "token_extractor.py", line 248, in <module>
  File "token_extractor.py", line 98, in login
  File "token_extractor.py", line 43, in login_step_1
  File "site-packages\requests\sessions.py", line 555, in get
  File "site-packages\requests\sessions.py", line 542, in request
  File "site-packages\requests\sessions.py", line 655, in send
  File "site-packages\requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='account.xiaomi.com', port=443): Max retries exceeded with url: /pass/serviceLogin?sid=xiaomiio&_json=true (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)')))
[30284] Failed to execute script token_extractor

**Comment by PiotrMachowski** [comment]
Network traffic was probably blocked, see #18

**Comment by drorya1** [comment]
You are correct
This is indeed local issue with my PC
Checking again
Thx !

**Comment by razorface1978** [comment]
<img width="1920" alt="Screen Shot 2022-04-30 at 8 39 51 AM" src="https://user-images.githubusercontent.com/58651991/166106106-8cb1b21c-dbf3-4161-a484-4c16611232bf.png">

not sure what im doing wrong but I get this every time I'm on a pi 3b+

**Comment by PiotrMachowski** [comment]
Have you tried docker version?

**Comment by razorface1978** [comment]
I have a Mac m1 and docker sucks on it I’ve tried but thank you for responding

**Comment by PiotrMachowski** [comment]
Buuut you can use docker script in HA terminal

**Comment by razorface1978** [comment]
Oh ok I’ll try it let you know what I get 
Thank you

**Comment by razorface1978** [comment]
Ok this is what I get running the docker code
