### ISSUE TITLE
Windows Token Extractor Error

### ISSUE THREAD

**Issue by cihanulusoy** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#82]
The token_extractor.exe found at https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/releases/latest/download/token_extractor.exe gives the following error:

Traceback (most recent call last):
File "site-packages\requests\compat.py", line 11, in
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "token_extractor.py", line 11, in
File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
File "site-packages\requests_init_.py", line 45, in
File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
File "site-packages\requests\exceptions.py", line 9, in
File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
File "site-packages\requests\compat.py", line 13, in
File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
File "site-packages\charset_normalizer_init_.py", line 24, in
File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
File "site-packages\charset_normalizer\api.py", line 5, in
File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
File "site-packages\charset_normalizer\cd.py", line 9, in
ModuleNotFoundError: No module named 'charset_normalizer.md__mypyc'
[15272] Failed to execute script token_extractor

Could you help please?

**Comment by PiotrMachowski** [comment]
It seems that this was a problem with action that generated the exe file. I have replaced it with one compiled manually and applied a fix that should resolve this issue for future builds

**Comment by cihanulusoy** [comment]
Dear Piotr,Well done. Thank you. I’ll buy you a coffee. Regards,Cihan ULUSOYOn 28 Jan 2023, at 05:24, Piotr Machowski ***@***.***> wrote:﻿
It seems that this was a problem with action that generated the exe file. I have replaced it with one compiled manually and applied a fix that should resolve this issue for future builds
